### ISSUE TITLE
Healthcheck

### ISSUE THREAD

**Issue by steklopod** [RanadeepPolavarapu/docker-nginx-http3#42]
I have healthcheck in my `docker-compose` file:

```yml
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
```

It works in official image, but not works in `ranadeeppolavarapu/nginx-http3` :-(

When I do `docker ps` in terminal I see `(unhealthy)` status:
```sh
629265e849ee   nginx    "nginx -g 'daemon of…"   5 minutes ago    Up 5 minutes (unhealthy)   0.0.0.0:443->443/tcp, :::443->443/tcp       nginx

```
But it works

**Comment by steklopod** [comment]
I wasted 1 day for solution. My hack was to change `CMD` to `CMD-SHELL`. This solution gives  `(healthy)` status:
```yml
  nginx:
    container_name: nginx
    build: ./nginx
      test: ["CMD-SHELL", "if [ -e /var/run/nginx.pid ]; then echo 0; else echo 1; fi"]
```
___
### Unsuccessfully:
I tried to add in nginx config:
```conf
  location  /health {
    default_type text/plain;
    return 200 "healthy\n";
  }
```
And in `docker-comose.yml`:
```yml
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://nginx:80/health"]
```
